defaultPortal: sandbox
portals:
  - name: sandbox
    portalId: 25563024
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CP6VweuBMBIJAA0AAAAA4A0DGJCfmAwg8uHNDSju6QwyFN5ajWRbnV4q8ArbKfUCAS8hANMUOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhSZfynXsd8hBeKFNkqyy3GCMxAxAUoDZXUxUgBaAA
        expiresAt: '2022-04-12T11:02:20.161Z'
    personalAccessKey: >-
      CiRldTEtZmZkMy0yYTgxLTQ5NjktOGIyYy02YzgxNDJhM2ZhYTUQkJ-YDBjy4c0NKhkABeaRgvvkOLD0yz6HUoncccyE1TaesyzYSgNldTE
